name: CI build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: prepare
      run: sudo apt-get update && sudo apt-get install build-essential meson libgtk-3-dev libmagickwand-dev libarchive-dev libpoppler-glib-dev libavformat-dev libavcodec-dev libswscale-dev libavutil-dev libwebp-dev
    - name: configure
      run: meson setup builddir
    - name: make
      run: meson compile -C builddir
    - name: check
      run: builddir/pqiv --version
